sudo: false
language: python
# cache package wheels (1 cache per python version)
cache: pip
python: 3.5

install:
  - pip install .[test]

script:
  - python -m pytest tests/

- name: Build and push Docker images
  uses: docker/build-push-action@v1.1.0

